[package]
name = "egreet"
version = "0.1.0"
edition = "2021"
description = "Simple greetd greeter, based on Relm4"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.1.4", features = ["derive"] }
const_format = "0.2.26"
file-rotate = "0.7.0"
glob = "0.3.0"
greetd_ipc = { version = "0.8.0", features = ["sync-codec"] }
log = "0.4.17"
lru = "0.7.8"
pwd = "1.4.0"
regex = "1.6.0"
relm4 = "0.5.0-rc.1"
serde = { version = "1.0.142", features = ["derive"] }
shlex = "1.1.0"
simplelog = "0.12.0"
thiserror = "1.0.32"
toml = "0.5.9"
tracker = "0.2.0"
