# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "egreet"
version = "0.1.0"
edition = "2021"
description = "Simple greetd greeter, based on Relm4"
license = "GPL-3.0-or-later"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.1.4", features = ["derive"] }
const_format = "0.2.26"
file-rotate = "0.7.0"
glob = "0.3.0"
greetd_ipc = { version = "0.9.0", features = ["sync-codec"] }
lru = "0.9.0"
pwd = "1.4.0"
regex = "1.7.1"
relm4 = "0.5.0-rc.1"
serde = { version = "1.0.142", features = ["derive"] }
shlex = "1.1.0"
thiserror = "1.0.32"
toml = "0.6.0"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["local-time"] }
tracker = "0.2.0"
